library(rvest)
url<-"https://books.toscrape.com/"
html_content=read_html(url)
class(html_content)
html_content
title_xpath='//*[@class="product_pod"]/h3/a'
price_xpath='//*[@class="product_pod"]/div[2]/p[1]'
title<-html_content%>%html_nodes(xpath=title_xpath)%>%html_text()%>%trimws()
price<-html_content%>%html_nodes(xpath=price_xpath)%>%html_text()%>%trimws()
books_data<-data.frame(Title=title,Price=price)
print(books_data)
write.csv(books_data,"write.txt")